// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwLt-BXXFXjTl6umdiMGGJtJ_gJFPmjv0',
    appId: '1:85925713100:web:36769a744597d256335e69',
    messagingSenderId: '85925713100',
    projectId: 'opportune-d9f55',
    authDomain: 'opportune-d9f55.firebaseapp.com',
    storageBucket: 'opportune-d9f55.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO-_VpkQlnfJ8KWBLE-qCAr4ttjuL-C88',
    appId: '1:85925713100:android:97d5a521d50c1347335e69',
    messagingSenderId: '85925713100',
    projectId: 'opportune-d9f55',
    storageBucket: 'opportune-d9f55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSgbTyAm-yYRhCIGoIBGnNsDEHb1QM4-Y',
    appId: '1:85925713100:ios:21f558ca07205dfb335e69',
    messagingSenderId: '85925713100',
    projectId: 'opportune-d9f55',
    storageBucket: 'opportune-d9f55.appspot.com',
    iosClientId: '85925713100-84us8ursjs4533corak5egu9iktl18ne.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSgbTyAm-yYRhCIGoIBGnNsDEHb1QM4-Y',
    appId: '1:85925713100:ios:d7144013d017d36b335e69',
    messagingSenderId: '85925713100',
    projectId: 'opportune-d9f55',
    storageBucket: 'opportune-d9f55.appspot.com',
    iosClientId: '85925713100-t524sc9emcag2q994eqbi896bhvebgf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockManagement.RunnerTests',
  );
}
